### ISSUE TITLE
Creating chat channel too fast

### ISSUE THREAD

**Issue by Stanzilla** [TheBackstabi/WorldQuestParty#2]
When first joining/creating the chat channel on login, the addon does not wait long enough for the players other channels to load so it always steals the first channel slot instead of one at the end, causing the player's channel to all shift by one, as in General is 2, Trade 3 etc.

**Comment by TheBackstabi** [comment]
Yep, I've fixed this locally, but still working on other issues before I can push it up. Next build should have filtering for Pet Battles/Professions, and fix this bug.

**Comment by TheBackstabi** [comment]
This has now been fixed.
