### ISSUE TITLE
Lua error 'ButtonThrottle' (a nil value)

### ISSUE THREAD

**Issue by cremor** [TheBackstabi/WorldQuestParty#3]
Got this error a few times today. No idea what exactly triggered it, sorry.

```
WorldQuestParty\WorldQuestParty-BFA-1.7.lua:205: attempt to call global 'ButtonThrottle' (a nil value)
WorldQuestParty\WorldQuestParty-BFA-1.7.lua:205: in function <WorldQuestParty\WorldQuestParty.lua:199>
(tail call): ?
```

Btw, I'm 100% sure that I'm using the latest version 1.8.1. The error message just says 1.7 because you didn't update the version in the toc file.

Unrelated to this issue: I suggest to configure CurseForge to link to the GitHub ticket tracker (like it links the source already). That will make it easier for people to find it.

**Comment by TheBackstabi** [comment]
Aye, I've fixed this on my end. Should have it up along with the options menu later today.

Thanks for the report~

**Comment by TheBackstabi** [comment]
This is fixed now.
