### ISSUE TITLE
RU support Localization.

### ISSUE THREAD

**Issue by Gekkafear** [TheBackstabi/WorldQuestParty#5]
Hello dear Author! I like this addon on EU server, but he didn't work on RU realm. So today I'm translate some text English>Russian and add WorldQuestParty_Locale.lua for this code:
`ruRU = { ruRU = { SEARCHING = "Поиск...", JOIN = "Вступить в группу", JOINING = "Запросить группу!", NO_PARTIES = "Групп не обнаружено!", NEW = "Создать группу", ENLIST = "Список групп", DELIST = "Убрать группу", POST = "Сообщение в ЛФГ", LISTED = "Найденные группы", UNLISTED = "Убрать группу из поиска", FULL = "Полная группа", WAITING = "Ожидание статуса группы...", LFM = "ЛФГ %s WQ - пишите мне \"wq\" для вступления! (World Quest Party)", COMPLETE = "Задание выполнено %s WQ. Спасибо за вашу помощь! (World Quest Party)", LEAVE = "Покинуть группу", PROMPT = "Покинуть группу?", YES = "Да", NO = "Нет", SLASH = "Если вы столкнулись с проблемой, пожалуйста обратитсь в поддержку на сайте!\n\nWQP Вспомогательные комманды:\nreset - очистка и перезагрузка кэша аддона.", RESET = "WQP: Все установлено, аддон будет перезагружен!" },`

Can you add this code in your addon for russian player? Thanks regards Yauhen.
P.S. If you don't see some russian text, add Cyrillic font or UTF-8.

**Comment by TheBackstabi** [comment]
Heyo, thanks for this. I'll get it added for the next version, which should be later this week.

**Comment by TheBackstabi** [comment]
So, everything seems almost good to go, I just have one question on the "Unlisted" string.

This string shows as a party member when your group isn't listed. The English text is "Party Delisted" - meaning the group is not currently listed. Your text seems to roughly mean "Remove group from search", which applies more to the "Delist" string.

For my actual question; would "группа не найдена" be an accurate translation for "Group not found"? This is what google gives, and is closer in meaning to the "Listed" string, which displays when the group is listed.

**Comment by TheBackstabi** [comment]
This has been added into version 1.10

Thanks again for the help.
