### ISSUE TITLE
AddOn still now working since 2 Weeks -> no LUA Errors

### ISSUE THREAD

**Issue by fubaWoW** [TheBackstabi/WorldQuestParty#6]
Hi there,
I've now tried your AddOn 3 times and it still does nothing except pop up the Button Frame.

If i click **ANY** of the Buttons like "Create Group" it does nothing...

The only AddOn that **may** can conflict in my case is World Quest List, but im not about to Disable it or even Try it because of a non Working AddOn!

People wonder why so less people use WorldQuestParty seems to be clear if it is no Working ;)

**Comment by fubaWoW** [comment]
Awesome Aupport ;)
Just closed.
No even a suggestions HOW the shit could work or any idea how you can fix it!
Just ... **AWESOME!**

**Comment by TheBackstabi** [comment]
I believe I've explained before how (or why) you're running into issues on the curseforge page.

I feel no qualms about not responding to someone throwing insults.
